version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "django-insecure-p)^5i@33!)v)l7*c#q)%j(g5d+**-yo%)6l*vg!gs_w-e=^_ig"
      DEBUG: "True"
      DB_ENGINE: "django.db.backends.sqlite3"
      DB_NAME: "db.sqlite3"
    depends_on:
      - db

  db:
    image: "sqlite"
    volumes:
      - ./data/db:/usr/src/app/db
