# Generated by Django 5.0.4 on 2024-06-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pet_weight_provider_address_vet_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
