# Generated by Django 5.0.4 on 2024-05-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_provider_address_alter_medicine_dosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosis',
            field=models.IntegerField(),
        ),
    ]
